// Dosa Point Menu Database (All 22 Authentic Items from Menu Card)
const MENU_ITEMS = [
  {
    id: 1,
    name: "Masala Dosa",
    category: "dosa",
    categoryName: "Signature Dosas",
    price: 110,
    isBestseller: true,
    spiceLevel: "Medium",
    rating: 4.8,
    reviewsCount: 342,
    image: "assets/images/hero_dosa.jpg",
    description: "The timeless classic! Thin, crispy golden fermented crepe filled with fragrant spiced potato masala, served with piping hot drumstick sambar and trio of chutneys.",
    tags: ["Classic", "Bestseller", "Pure Ghee"],
    customizable: true
  },
  {
    id: 2,
    name: "Plain Dosa",
    category: "dosa",
    categoryName: "Signature Dosas",
    price: 100,
    isBestseller: false,
    spiceLevel: "Mild",
    rating: 4.7,
    reviewsCount: 198,
    image: "assets/images/plain_dosa.jpg",
    description: "Golden, paper-thin, crispy rice and lentil crepe roasted to perfection. Perfect for breakfast or light snacking with fresh coconut and tomato chutney.",
    tags: ["Light & Crispy", "Classic"],
    customizable: true
  },
  {
    id: 3,
    name: "Special Masala Dosa",
    category: "dosa",
    categoryName: "Signature Dosas",
    price: 150,
    isBestseller: true,
    isChefSpecial: true,
    spiceLevel: "Spicy",
    rating: 4.9,
    reviewsCount: 520,
    image: "assets/images/hero_dosa.jpg",
    description: "Chef's signature recipe with a double-layered spiced potato filling, roasted cashew nuts, secret blend of 83 Madras Cafe heirloom spices, and roasted crisp.",
    tags: ["Chef's Special", "Must Try", "Rich"],
    customizable: true
  },
  {
    id: 4,
    name: "Ghee Masala Dosa",
    category: "dosa",
    categoryName: "Signature Dosas",
    price: 150,
    isBestseller: true,
    spiceLevel: "Medium",
    rating: 4.9,
    reviewsCount: 410,
    image: "assets/images/hero_dosa.jpg",
    description: "Generously bathed in pure golden desi ghee on the tawa. Imparts an irresistible aroma, deeply crisp caramelized texture, and heavenly flavor.",
    tags: ["Pure Desi Ghee", "Aromatic", "Bestseller"],
    customizable: true
  },
  {
    id: 5,
    name: "Podi Ghee Dosa",
    category: "dosa",
    categoryName: "Signature Dosas",
    price: 150,
    isBestseller: true,
    isChefSpecial: true,
    spiceLevel: "Spicy",
    rating: 4.9,
    reviewsCount: 388,
    image: "assets/images/podi_dosa.jpg",
    description: "Coated generously with aromatic Tamil gunpowder (milagai podi) and sizzling hot pure desi ghee. Fiery, nutty, intensely flavorful South Indian heritage favorite.",
    tags: ["Gunpowder Podi", "Desi Ghee", "Spicy Delight"],
    customizable: true
  },
  {
    id: 6,
    name: "Onion Masala Dosa",
    category: "dosa",
    categoryName: "Signature Dosas",
    price: 140,
    isBestseller: false,
    spiceLevel: "Medium",
    rating: 4.7,
    reviewsCount: 175,
    image: "assets/images/hero_dosa.jpg",
    description: "Crisp golden crepe loaded with sweet caramelized onions sautéed with green chillies, folded around seasoned turmeric potato filling.",
    tags: ["Crunchy Onion", "Savory"],
    customizable: true
  },
  {
    id: 7,
    name: "Onion Dosa",
    category: "dosa",
    categoryName: "Signature Dosas",
    price: 130,
    isBestseller: false,
    spiceLevel: "Mild",
    rating: 4.6,
    reviewsCount: 140,
    image: "assets/images/plain_dosa.jpg",
    description: "Dosa batter cooked with a generous scattering of finely chopped sweet onions on the sizzling tawa, offering a wonderful crisp and crunchy bite.",
    tags: ["Crunchy", "Simple"],
    customizable: true
  },
  {
    id: 8,
    name: "Onion Uttapam",
    category: "uttapam",
    categoryName: "Soft & Thick Uttapams",
    price: 130,
    isBestseller: false,
    spiceLevel: "Mild",
    rating: 4.7,
    reviewsCount: 210,
    image: "assets/images/uttapam.jpg",
    description: "Thick, pillowy soft fermented rice pancake cooked gently on low flame, crowned with a plentiful layer of golden pan-roasted chopped onions and green chillies.",
    tags: ["Soft & Fluffy", "Comfort Food"],
    customizable: true
  },
  {
    id: 9,
    name: "Onion Tomato Uttapam",
    category: "uttapam",
    categoryName: "Soft & Thick Uttapams",
    price: 120,
    isBestseller: true,
    spiceLevel: "Mild",
    rating: 4.8,
    reviewsCount: 265,
    image: "assets/images/uttapam.jpg",
    description: "Vibrant and tangy! Plump, juicy red country tomatoes and sweet crunchy onions pressed into a thick spongy rice cake, seasoned with fresh coriander.",
    tags: ["Tangy & Juicy", "Popular"],
    customizable: true
  },
  {
    id: 10,
    name: "Mix Veg. Uttapam",
    category: "uttapam",
    categoryName: "Soft & Thick Uttapams",
    price: 130,
    isBestseller: false,
    spiceLevel: "Mild",
    rating: 4.6,
    reviewsCount: 180,
    image: "assets/images/uttapam.jpg",
    description: "A colorful garden atop a soft uttapam base: finely diced carrots, capsicum, onions, tomatoes, and aromatic curry leaves cooked until tender.",
    tags: ["Healthy", "Vibrant"],
    customizable: true
  },
  {
    id: 11,
    name: "Paneer Uttapam",
    category: "uttapam",
    categoryName: "Soft & Thick Uttapams",
    price: 170,
    isBestseller: true,
    isChefSpecial: true,
    spiceLevel: "Medium",
    rating: 4.9,
    reviewsCount: 315,
    image: "assets/images/uttapam.jpg",
    description: "Luxuriously topped with soft cottage cheese (paneer) cubes, lightly spiced with chaat masala, onions, and herbs. Rich, protein-packed, and comforting.",
    tags: ["Rich Paneer", "Chef's Special"],
    customizable: true
  },
  {
    id: 12,
    name: "Paneer Masala Dosa",
    category: "dosa",
    categoryName: "Signature Dosas",
    price: 170,
    isBestseller: true,
    spiceLevel: "Medium",
    rating: 4.8,
    reviewsCount: 295,
    image: "assets/images/hero_dosa.jpg",
    description: "Golden crispy tawa crepe stuffed with a hearty blend of fresh grated paneer, roasted onions, mild green chillies, and traditional potato masala.",
    tags: ["Paneer Lover", "Heavy"],
    customizable: true
  },
  {
    id: 13,
    name: "Rava Masala Dosa",
    category: "rava",
    categoryName: "Crispy Rava Specials",
    price: 150,
    isBestseller: true,
    spiceLevel: "Medium",
    rating: 4.8,
    reviewsCount: 340,
    image: "assets/images/rava_dosa.jpg",
    description: "Net-like lacy semolina crepe, crackling crisp with cumin seeds, crushed black pepper, chopped ginger, and loaded with spiced potato stuffing.",
    tags: ["Lacy Crispy", "Semolina Delight"],
    customizable: true
  },
  {
    id: 14,
    name: "Rava Onion Dosa",
    category: "rava",
    categoryName: "Crispy Rava Specials",
    price: 150,
    isBestseller: false,
    spiceLevel: "Mild",
    rating: 4.7,
    reviewsCount: 165,
    image: "assets/images/rava_dosa.jpg",
    description: "Ultra-crisp roasted rava dosa generously sprinkled with finely chopped shallots and cilantro, giving each mouthful an addictive crunch.",
    tags: ["Super Crunchy", "Rava Special"],
    customizable: true
  },
  {
    id: 15,
    name: "Butter Masala Dosa",
    category: "dosa",
    categoryName: "Signature Dosas",
    price: 120,
    isBestseller: true,
    spiceLevel: "Medium",
    rating: 4.8,
    reviewsCount: 420,
    image: "assets/images/hero_dosa.jpg",
    description: "Smothered with generous dollops of creamy butter on the hot tawa. Melt-in-mouth golden crispness folded with our special spiced potato mash.",
    tags: ["Extra Butter", "Indulgent"],
    customizable: true
  },
  {
    id: 16,
    name: "Butter Plain",
    category: "dosa",
    categoryName: "Signature Dosas",
    price: 120,
    isBestseller: false,
    spiceLevel: "Mild",
    rating: 4.6,
    reviewsCount: 135,
    image: "assets/images/plain_dosa.jpg",
    description: "Simple yet glorious: roasted thin crepe drenched in rich melting butter, creating a golden glazed crackling surface.",
    tags: ["Buttery Crisp", "Classic"],
    customizable: true
  },
  {
    id: 17,
    name: "Mysore Masala Dosa",
    category: "dosa",
    categoryName: "Signature Dosas",
    price: 130,
    isBestseller: true,
    isChefSpecial: true,
    spiceLevel: "Spicy",
    rating: 4.9,
    reviewsCount: 480,
    image: "assets/images/podi_dosa.jpg",
    description: "The pride of South India! Crepe smeared with fiery red garlic-chilli chutney and tangy spices on the inner side, filled with buttered potato masala.",
    tags: ["Fiery Red Chutney", "Legendary", "Spicy"],
    customizable: true
  },
  {
    id: 18,
    name: "Sambar Vada",
    category: "tiffin",
    categoryName: "Traditional Tiffins",
    price: 90,
    isBestseller: true,
    spiceLevel: "Medium",
    rating: 4.9,
    reviewsCount: 512,
    image: "assets/images/idli_vada.jpg",
    description: "Two crispy, golden deep-fried urad dal medu vadas submerged in a steaming earthen bowl of aromatic lentil drumstick sambar, topped with freshly grated coconut.",
    tags: ["Crisp & Dipped", "Morning Favorite"],
    customizable: false
  },
  {
    id: 19,
    name: "Idly Sambar",
    category: "tiffin",
    categoryName: "Traditional Tiffins",
    price: 90,
    isBestseller: true,
    spiceLevel: "Mild",
    rating: 4.8,
    reviewsCount: 450,
    image: "assets/images/idli_vada.jpg",
    description: "Soft as clouds! Two traditional steamed fermented rice & black gram cakes served swimming in hot savory sambar with coconut and red tomato chutneys.",
    tags: ["Pillow Soft", "Healthy", "Comfort"],
    customizable: false
  },
  {
    id: 20,
    name: "Veg. Chowmein (Full)",
    category: "chinese",
    categoryName: "Indo-Chinese Chowmein",
    price: 120,
    isBestseller: false,
    spiceLevel: "Medium",
    rating: 4.6,
    reviewsCount: 220,
    image: "assets/images/chowmein.jpg",
    description: "Desi street-style wok-tossed noodles with shredded cabbage, crunchy carrots, bell peppers, soy sauce, and aromatic garlic spices. Full hearty portion.",
    tags: ["Desi Wok", "Full Plate"],
    customizable: true
  },
  {
    id: 21,
    name: "Chilli Garlic Chowmein",
    category: "chinese",
    categoryName: "Indo-Chinese Chowmein",
    price: 140,
    isBestseller: true,
    spiceLevel: "Spicy",
    rating: 4.7,
    reviewsCount: 275,
    image: "assets/images/chowmein.jpg",
    description: "Smoky wok-fried noodles infused with roasted garlic flakes, hot red chilli paste, and crunchy spring onions. Zingy, spicy, and packed with flavor.",
    tags: ["Spicy Chilli Garlic", "Bestseller"],
    customizable: true
  },
  {
    id: 22,
    name: "Paneer Chowmein",
    category: "chinese",
    categoryName: "Indo-Chinese Chowmein",
    price: 160,
    isBestseller: true,
    spiceLevel: "Medium",
    rating: 4.8,
    reviewsCount: 290,
    image: "assets/images/chowmein.jpg",
    description: "Wok-fried noodles loaded with golden spiced paneer cubes, tossed with crisp bell peppers, onions, and dark seasoned oriental sauce.",
    tags: ["Paneer Loaded", "Crowd Favorite"],
    customizable: true
  }
];

const SHOP_CONFIG = {
  name: "Dosa Point",
  parentBrand: "A chain of 83 Madras Cafe",
  tagline: "Serving with love since 1983",
  address: "Shop Number 69, Netaji Nagar Market",
  phone: "7290995566",
  whatsappNumber: "917290995566",
  timings: "09:00 AM - 09:30 PM",
  minDeliveryAmount: 350,
  currency: "₹",
  freeDeliveryThreshold: 500,
  deliveryFee: 30
};
